### ISSUE TITLE
Luck of the irish

### ISSUE THREAD

**Issue by Arias3k** [gliscowo/things#27]
I tried using this trinket but im not sure how it works exactly I equipped it in the right slot, and I had saved 6 poisonous potatoes in a chest until i made this ive re dropped and picket them up and it wont work am I doing this wrong?..

**Comment by gliscowo** [comment]
I would recommend reading the entry in the Almanac, it explains what the Trinket does and how you use it
Cheers

**Comment by Arias3k** [comment]
aight thanks
